{
 "title": "Custom logs",
 "description": "Custom logs monitoring using Loki",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"log-exporter\"} | json timening=\"timing\" | unwrap timening [$__range])"
    }
   ]
  },
  {
   "title": "Average by Top 3 Paths (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, avg_over_time({job=\"log-exporter\"} | json timening=\"timing\", path=\"path\" | unwrap timening [$__range]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "by Paths",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{job=\"log-exporter\"} | json"
    }
   ]
  },
  { "title": "Number of Processed Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "by Paths",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"log-exporter\"} | json"
    }
   ]
  },
  {
   "title": "by Container Name",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"log-exporter\"} | json container=\"container\" [$__range])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "by Device",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"log-exporter\"} | json device=\"dt\" [$__range])",
     "legendFormat": "{{device}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "by Status Code",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"log-exporter\"} | json status=\"status\" [$__range])",
     "legendFormat": "{{status}}",
     "resolution": 1
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{job=\"log-exporter\"} | json | level = `error`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{job=\"log-exporter\"} | json | level = `warn`"
    }
   ]
  }
 ]
}